# Generated by Django 5.0.4 on 2024-04-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="last_updated_date",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
